# Generated by Django 2.0.6 on 2020-07-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentNuber', models.CharField(max_length=20, verbose_name='当前数据')),
            ],
            options={
                'verbose_name_plural': '当前数据表',
                'verbose_name': '当前数据表',
                'db_table': 'current_number',
            },
        ),
        migrations.AlterModelOptions(
            name='datanumber',
            options={'verbose_name': '动态数据表', 'verbose_name_plural': '动态数据表'},
        ),
    ]
