# Generated by Django 2.0.6 on 2020-07-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiwebsite', '0002_auto_20200730_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentnumber',
            old_name='currentNuber',
            new_name='currentNumber',
        ),
    ]
